### ISSUE TITLE
Reusing your line

### ISSUE THREAD

**Issue by jswetzen** [varju/docker-plexconnect#3]
Hi, I'm about to create my own [docker-plexconnect](https://github.com/jswetzen/docker-plexconnect) that's up-to-date, taking inspiration from different projects. Since you haven't specified a license for your code, I want to ask if I can copy your line verbatim in my project since it really handles the settings neatly.

https://github.com/varju/docker-plexconnect/blob/e4e20375056fad6a4e60167f5e5646e0b2fbe140/start-plexconnect.sh#L26

**Comment by varju** [comment]
Sorry, I never saw this question until today. Yes, you can use it!
